package com.zjianhao.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "AIR_CMD".
 */
public class AirCmd {

    private Long id;
    private Integer device_id;
    private String cmd;
    private Integer temp;
    private String data;

    public AirCmd() {
    }

    public AirCmd(Long id) {
        this.id = id;
    }

    public AirCmd(Long id, Integer device_id, String cmd, Integer temp, String data) {
        this.id = id;
        this.device_id = device_id;
        this.cmd = cmd;
        this.temp = temp;
        this.data = data;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getDevice_id() {
        return device_id;
    }

    public void setDevice_id(Integer device_id) {
        this.device_id = device_id;
    }

    public String getCmd() {
        return cmd;
    }

    public void setCmd(String cmd) {
        this.cmd = cmd;
    }

    public Integer getTemp() {
        return temp;
    }

    public void setTemp(Integer temp) {
        this.temp = temp;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }

}
