package com.zjianhao.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DEVICE".
 */
public class Device {

    private Long id;
    private Integer type_id;
    private Integer brand_id;
    private Integer device_id;
    private String device_name;
    private Long backup_time;

    public Device() {
    }

    public Device(Long id) {
        this.id = id;
    }

    public Device(Long id, Integer type_id, Integer brand_id, Integer device_id, String device_name, Long backup_time) {
        this.id = id;
        this.type_id = type_id;
        this.brand_id = brand_id;
        this.device_id = device_id;
        this.device_name = device_name;
        this.backup_time = backup_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getType_id() {
        return type_id;
    }

    public void setType_id(Integer type_id) {
        this.type_id = type_id;
    }

    public Integer getBrand_id() {
        return brand_id;
    }

    public void setBrand_id(Integer brand_id) {
        this.brand_id = brand_id;
    }

    public Integer getDevice_id() {
        return device_id;
    }

    public void setDevice_id(Integer device_id) {
        this.device_id = device_id;
    }

    public String getDevice_name() {
        return device_name;
    }

    public void setDevice_name(String device_name) {
        this.device_name = device_name;
    }

    public Long getBackup_time() {
        return backup_time;
    }

    public void setBackup_time(Long backup_time) {
        this.backup_time = backup_time;
    }

}
