package com.zjianhao.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "KEYAS".
 */
public class Keyas {

    private Long id;
    private Integer device_id;
    private String cmd;
    private String name;
    private String data;

    public Keyas() {
    }

    public Keyas(Long id) {
        this.id = id;
    }

    public Keyas(Long id, Integer device_id, String cmd, String name, String data) {
        this.id = id;
        this.device_id = device_id;
        this.cmd = cmd;
        this.name = name;
        this.data = data;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getDevice_id() {
        return device_id;
    }

    public void setDevice_id(Integer device_id) {
        this.device_id = device_id;
    }

    public String getCmd() {
        return cmd;
    }

    public void setCmd(String cmd) {
        this.cmd = cmd;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }

}
